### DISCUSSION TITLE
How to deal with multiple Contexts in Hierarchical and Parallel State Machines?

### DISCUSSION THREAD

**Discussion by a-y-u-s-h** [statelyai/xstate#1528] [Q&A] [answered]
Hi, 

Docs say that `context` property is valid for any state node. I couldn't find information about how to deal with multiple contexts in a state machine representation. Or how to deal with hierarchical state machines where there's a context on more than one level of hierarchy. Or contexts which are present in child state nodes of a parallel machine as well. Take this state machine for example - This describes a generic state machine for a web application route -  

![2020-10-05_12-51-15_screenshot](https://user-images.githubusercontent.com/19586719/95050627-8442c300-0709-11eb-8921-73791c0aff43.png)

```yaml
id: home
type: parallel
context:
states:
  display:
    #  ======================================
    #    Display machine's context contains 
    #    information about the states of 'content' 
    #    that's displayed on the screen and the styles
    #    of different components on the screen.
    #  ======================================
    type: parallel
    context:
      styles:
      context:
    states:
      styles:
        #  ======================================
        #    Context for styles is calculated
        #    by merging metadata of current states
        #    of `layout` and `theme` child state nodes.
        #    This allows us to later send an event to
        #    toggle between themes and layouts independently.
        #  ======================================
        type: parallel
        context:
        states:
          layout:
            #  ======================================
            #    Layout doesn't require to have its
            #    own context, but each state of this
            #    compound state have some metadata associated
            #    with it, describing the props to be passed
            #    to components when machine is in a particular state.
            #    Layout state's metadata describe how things are arranged.
            #  ======================================
            initial: default
            states:
              default:
                on:
                  next.layout:
                    target: facebook
                meta:
              facebook:
                on:
                  next.layout:
                    target: instagram
                meta:
              instagram:
                on:
                  next.layout:
                    target: default
                meta:
          theme:
            #  ======================================
            #    Theme doesn't require to have its
            #    own context, but each state of this
            #    compound state have some metadata associated
            #    with it, describing the props associated with color 
            #    to be passed to components when machine is in a particular state.
            #    Theme state's metadata describe how things are colored.
            #  ======================================
            initial: default
            states:
              default:
                on:
                  next.theme:
                    target: darkula
                meta:
              darkula:
                on:
                  next.theme:
                    target: monokai
                meta:
              monokai:
                on:
                  next.theme:
                    target: default
                meta:
      content:
        initial: default
        states:
          default:
            meta:
```

In the above YAML representation of a state machine - as I change the layout or theme based on events, I want to trigger actions that merge the metadata of current state of `layout` and `theme` and store it in context of `styles`, which I can access in lifecycle of a React component and see different layouts and color schemes being applied in real time based on different events.

However, I have no idea how to deal with `contexts` in a hierarchy. The `context` property doesn't return contexts of entire active hierarchy - it only returns contexts of root node. Also, I don't know how to change context of child state in actions. The context that we get in actions should be the context of the immediate compound state in the tree and not always the root node (or maybe always merged contexts of entire tree). 

Also, Is this the way to approach it? In this case, I may not always want to break this into different state machines and then invoke them as actors because I may want to have different layout states for different pages and could get very ugly. I wonder if there's easy ways to deal with multiple contexts in the hierarchy of states.
