### DISCUSSION TITLE
@xstate/test - How to parametrize tests?

### DISCUSSION THREAD

**Discussion by a-y-u-s-h** [statelyai/xstate#1632] [Q&A] [answered]
We can parametrize actions, activities, guards and services as a string while writing out the representation of state machine. I really like this pattern and in my all projects I keep the JSON/YAML representation separate from actions JS in their own YAML files. I would like to know if there's a way yet to allow us to parametrize test functions or whether that's on the todo list (not sure where that is).

Docs say that `test` key should be present in `meta` key, and if I describe my machine in YAML file, there's no way I can attach an async function for puppeteer in YAML file, so it needs to live somewhere else. For example, if this is the state machine (with tests):

```js
const toggleMachine = Machine({
  id: 'toggle',
  initial: 'inactive',
  states: {
    inactive: {
      on: {
        /* ... */
      },
      meta: {
        test: async (page) => {
          await page.waitFor('input:checked');
        }
      }
    },
    active: {
      on: {
        /* ... */
      },
      meta: {
        test: async (page) => {
          await page.waitFor('input:not(:checked)');
        }
      }
    }
  }
});
```

It would be awesome to write it as (if not already supported):

```yaml
id: toggle
initial: inactive
states:
  inactive:
    on:
      activate: active
    meta:
      test: test-inactive-state
  active:
    on:
      deactivate: inactive
    meta:
      test: test-active-state

```

Or maybe not inside `meta` but an optional `tests` key maybe:

```yaml
id: toggle
initial: inactive
states:
  inactive:
    tests:
      - test-inactive-state
    on:
      activate: active
  active:
    tests:
      - test-active-state
    on:
      deactivate: inactive

```

And then add those `test-inactive-state` and `test-active-state` functions later inside an `options` object, when I pass it to `interpret` or maybe `createModel`. Is it not supported or not documented yet?
