### ISSUE TITLE
@xstate/test - Parametrizing Tests

### ISSUE THREAD

**Issue by a-y-u-s-h** [statelyai/xstate#1634]
**Description**
Not exactly a bug, but just opening an issue for feature request in [this discussion](https://github.com/davidkpiano/xstate/discussions/1632). Here's a quick summary:

- Currently, we can parametrize actions, activities, guards and services as a string while writing out the representation of state machine. This pattern is awesome and and I use it in my all projects I keep the JSON/YAML representation separate from actions JS in their own YAML files. But we can't parametrize `tests` yet because they live inside `meta` key which can contain strings, numbers and all sorts of things. 

- While writing a YAML file we there's no way to write an async function, so it would be nice to have a `test` or `tests` key which lives outside the JSON representation, in an `options` object which can be passed in when creating the machine, similar to `actions` and allow us to write tests associated with the state separately and parametrize it. For example machine below cannot be written into JSON/YAML format because it contains functions inside `meta` key:

```js
const toggleMachine = Machine({
  id: 'toggle',
  initial: 'inactive',
  states: {
    inactive: {
      on: {
        /* ... */
      },
      meta: {
        test: async (page) => {
          await page.waitFor('input:checked');
        }
      }
    },
    active: {
      on: {
        /* ... */
      },
      meta: {
        test: async (page) => {
          await page.waitFor('input:not(:checked)');
        }
      }
    }
  }
});
```
But if we could parametrize tests, this could be written as:

```yaml
id: toggle
initial: inactive
states:
  inactive:
    tests:
      - test-inactive-state
    on:
      activate: active
  active:
    tests:
      - test-active-state
    on:
      deactivate: inactive
```
And then we could add those `test-inactive-state` and `test-active-state` functions later inside an options object, when I pass it to `interpret` or maybe `createModel`.
